// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aaqriyjeruvyeuhzcilr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFhcXJpeWplcnV2eWV1aHpjaWxyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzNDQ2NTksImV4cCI6MjA2NjkyMDY1OX0.hnuG4e3f7xiAtCV3iZVICNpRJJenDuIHecdEcArXuMY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});